export enum EmergencySymptom {
  CHEST_PAIN,
  DIFFICULTY_BREATHING,
  LIGHTHEADEDNESS,
  DISORIENTATION,
}

export enum GeneralSymptom {
  FEVER_OR_CHILLS,
  DIFFICULTY_BREATHING,
  COUGH,
  LOSS_OF_SMELL_TASTE_APPETITE,
  VOMITING_OR_DIARRHEA,
  ACHING,
  OTHER,
}

export enum UnderlyingCondition {
  LUNG_DISEASE,
  HEART_CONDITION,
  WEAKENED_IMMUNE_SYSTEM,
  OBESITY,
  KIDNEY_DISEASE,
  DIABETES,
  LIVER_DISEASE,
  HIGH_BLOOD_PRESSURE,
  BLOOD_DISORDER,
  CEREBROVASCULAR_DISEASE,
  SMOKING,
  PREGNANCY,
}

export enum AgeRange {
  EIGHTEEN_TO_SIXTY_FOUR,
  SIXTY_FIVE_AND_OVER,
}
