ruby '2.6.5'
source "https://rubygems.org"

gem "bundler", "=2.2.1"
gem "cocoapods", "1.10.0"
gem "fastlane", "2.170.0"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
