require_relative "../node_modules/react-native/scripts/react_native_pods"
require_relative "../node_modules/@react-native-community/cli-platform-ios/native_modules"
platform :ios, "10.0"

project "COVIDSafePaths.xcodeproj",
  "Debug-BT" => :debug,
  "Release-BT" => :release,
  "Staging-BT" => :release

def shared_pods
  config = use_native_modules!
  use_react_native!(path: config["reactNativePath"])

  permissions_path = "../node_modules/react-native-permissions/ios"
  pod "Permission-Notifications", path: "#{permissions_path}/Notifications.podspec"

  pod "Realm", modular_headers: true
  pod "RealmSwift", modular_headers: true
  pod "Alamofire", "~> 4.9.1"
  pod "KeychainAccess", "~> 4.2.0"
  pod "ZIPFoundation", "~> 0.9.11"
  pod "PromisesSwift", modular_headers: true
  pod "PromisesObjC", modular_headers: true
end

target "BT" do
  shared_pods

  target "BTTests" do
    inherit! :search_paths
  end
end
