require_relative "../node_modules/react-native/scripts/react_native_pods"
require_relative "../node_modules/@react-native-community/cli-platform-ios/native_modules"
platform :ios, "13.5"

def shared_pods
  config = use_native_modules!
  use_react_native!(path: config["reactNativePath"])

  permissions_path = "../node_modules/react-native-permissions/ios"
  pod "Permission-Notifications", path: "#{permissions_path}/Notifications.podspec"

  pod "Realm", "~> 10.5.2", modular_headers: true
  pod "RealmSwift","~> 10.5.2", modular_headers: true
  pod "Alamofire", "~> 4.9.1"
  pod "KeychainAccess", "~> 4.2.0"
  pod "ZIPFoundation", "~> 0.9.11"
  pod "PromisesSwift", modular_headers: true
  pod "PromisesObjC", modular_headers: true

  use_flipper!('Flipper' => '0.86.0', 'Flipper-Folly' => '2.5.3')
  post_install do |installer|
    flipper_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target "BT" do
  shared_pods

  target "BTTests" do
    inherit! :search_paths
  end
end
