require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

project 'COVIDSafePaths.xcodeproj',
'Debug-BT' => :debug,
'Debug-GPS' => :debug,
'Release-BT' => :release,
'Release-GPS' => :release,
'Staging-BT' => :release,
'Staging-GPS' => :release

def pods
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

  pod 'Realm', :modular_headers => true
  pod 'RealmSwift', :modular_headers => true
  pod 'Alamofire', '~> 4.9.1'
  pod 'ZIPFoundation'
  pod 'Firebase/Crashlytics'
end

target 'BT' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pods

  target 'BTTests' do
    inherit! :search_paths
    pods
  end
end

