# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :deploy_to_appcenter do |options|
    # Push to AppCenter
    # more details: https://github.com/Microsoft/fastlane-plugin-appcenter/
    changeLogs = format_last_commit

      appcenter_upload(
        api_token: options[:apiToken],
        owner_name: "PathCheck",
        app_name: options[:appName],
        notify_testers: false,
        destinations: "Collaborators",
        release_notes: changeLogs,
        file: options[:ipa_path]
      )
    end

  desc "Format last commit"
  private_lane :format_last_commit do
    commit = last_git_commit
    "\nFrom: " + commit[:author] + "\n" +
    "Changes: " + commit[:message] +
    "Commit: " + commit[:commit_hash]
  end
end
