# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs Android (Native) unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a Debug AAB"
  lane :debug_bt do
    gradle(
      task: "clean assembleDebug",
      print_command: false,
    )
  end

  desc "Increment version code"
  lane :release_increment_version_code do |options|
    increment_version_code(
      gradle_file_path: "app/build.gradle",
      version_code: options[:versionCode]
    )
  end

  desc "Build a Release APK"
  lane :release_apk do |options|
    gradle(
      task: "assembleRelease",
      print_command: false,
      properties: {
        "android.injected.signing.store.password" => options[:keyStorePassword],
        "android.injected.signing.key.alias" => options[:keyAlias],
        "android.injected.signing.key.password" =>  options[:keyPassword]
      }
    )
  end

  desc "Build a Release AAB"
  lane :release_aab do |options|
    gradle(
      task: "bundle",
      build_type: "release",
      print_command: false,
      properties: {
        "android.injected.signing.store.password" => options[:keyStorePassword],
        "android.injected.signing.key.alias" => options[:keyAlias],
        "android.injected.signing.key.password" =>  options[:keyPassword]
      }
    )
  end

  desc "Submit APK to AppCenter"
  lane :android_alpha_apk do |options|
    # Push to AppCenter
    # more details: https://github.com/Microsoft/fastlane-plugin-appcenter/
    appcenter_upload(
      api_token: options[:apiToken],
      owner_name: "PathCheck",
      app_name: options[:appName],
      notify_testers: true,
      destinations: "Collaborators",
      file: "app/build/outputs/apk/release/app-release.apk"
    )
  end

  desc "Upload to google play store beta track"
  lane :play_store_bt do

    validate_play_store_json_key(
      json_key: "app/json_key.json",
    )

    upload_to_play_store(
      track: 'beta',
      release_status: 'draft',
      skip_upload_apk: true,
      package_name: 'org.pathcheck.covidsafepaths.bt',
      aab: "app/build/outputs/bundle/release/app-release.aab"
    )

  end

end
