name: i18n

on:
  push:
    branches: [develop]
    paths:
      - src/locales/en.json
      - src/locales/eula/en.html
      - ios/en.lproj/*.strings
      - android/app/src/main/res/values/strings.xml
      - .github/workflows/*.yml
      - src/locales/*.sh
  pull_request:
    branches: [develop]
    paths:
      - src/locales/en.json
      - src/locales/eula/en.html
      - ios/en.lproj/*.strings
      - android/app/src/main/res/values/strings.xml
      - .github/workflows/*.yml
      - src/locales/*.sh

jobs:
  # Run on PRs, checks for any added keys that are missing in the app/locales/en.json file
  check-i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: cached node_modules/
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - run: yarn --frozen-lockfile
        if: steps.cache.outputs.cache-hit != 'true'

      - run: yarn i18n:check
