name: i18n

on:
  push:
    branches: [develop]
    paths:
      - src/locales/en.json
      - src/locales/eula/en.html
      - ios/en.lproj/*.strings
      - android/app/src/main/res/values/strings.xml
      - .github/workflows/*.yml
      - src/locales/*.sh

jobs:
  lokalise-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: upload english files
        run: yarn i18n:push
        env:
          LOKALISE_READ_WRITE_TOKEN: ${{ secrets.LOKALISE_READ_WRITE_TOKEN }}
